version: "3.9"

services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    environment:
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      HONEYCOMB_DATASET: ${HONEYCOMB_DATASET}
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4320:4317" # OTLP gRPC
      - "4319:4318" # OTLP HTTP
      - "8888:8888" # Collector metrics
      - "9464:9464" # Prometheus exporter

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI only
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
