version: "3.9"

services:

  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - "18888:18888" 
      - "18889:18889"  
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    networks:
      - telemetry

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    environment:
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      HONEYCOMB_DATASET: ${HONEYCOMB_DATASET}
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4320:4317" # OTLP gRPC
    networks:
      - telemetry

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317" 

    networks:
      - telemetry

  product-management:
    build:
      context: .
      dockerfile: ./ProductManagement.Api/Dockerfile
    depends_on:
      - otel-collector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
    networks:
      - telemetry
    

  order-management:
    build:
      context: .
      dockerfile: ./OrderManagement.Api/Dockerfile
    depends_on:
      - otel-collector
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"
    networks:
      - telemetry
networks:
  telemetry:
    driver: bridge